name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.4, 8.3, 8.2]
        laravel: [12.*, 11.*, 10.*]
        stability: [prefer-stable]
        exclude:
          - php: 8.2
            laravel: 12.*
        include:
          - laravel: 12.*
            testbench: 10.*
            collision: '^8.4.0'
            pest: '^4.0'
            pest-laravel: '^4.0'
            larastan: '^3.7.2'
            phpstan-deprecation: '^2.0'
          - laravel: 11.*
            testbench: 9.*
            collision: '^8.4.0'
            pest: '^3.0'
            pest-laravel: '^3.0'
            larastan: '^3.7.2'
            phpstan-deprecation: '^2.0'
          - laravel: 10.*
            testbench: 8.*
            collision: '^7.0'
            pest: '^2.0'
            pest-laravel: '^2.0'
            larastan: '^2.0'
            phpstan-deprecation: '^1.0'

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        shell: bash
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nunomaduro/collision:${{ matrix.collision }}" "pestphp/pest:${{ matrix.pest }}" "pestphp/pest-plugin-laravel:${{ matrix.pest-laravel }}" "nunomaduro/larastan:${{ matrix.larastan }}" "phpstan/phpstan-deprecation-rules:${{ matrix.phpstan-deprecation }}" --dev --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        shell: bash
        run: XDEBUG_MODE=coverage ./vendor/bin/pest --coverage
